module DateValues
  VERSION: String

  class YearMonth
    include Comparable

    attr_reader year: Integer
    attr_reader month: Integer

    def initialize: (Integer year, Integer month) -> void

    def self.from: (Date date) -> YearMonth

    def self.parse: (String str) -> YearMonth

    def <=>: (YearMonth other) -> Integer
           | (untyped other) -> nil

    def +: (Integer n) -> YearMonth

    def -: (Integer n) -> YearMonth
         | (YearMonth other) -> Integer

    def succ: () -> YearMonth

    def advance: (?years: Integer, ?months: Integer) -> YearMonth

    def change: (?year: Integer, ?month: Integer) -> YearMonth

    def strftime: (String format) -> String

    def to_date: () -> Date

    def as_json: (*untyped) -> String

    def to_s: () -> String

    def inspect: () -> String
  end

  class MonthDay
    include Comparable

    attr_reader month: Integer
    attr_reader day: Integer

    def initialize: (Integer month, Integer day) -> void

    def self.from: (Date date) -> MonthDay

    def self.parse: (String str) -> MonthDay

    def <=>: (MonthDay other) -> Integer
           | (untyped other) -> nil

    def change: (?month: Integer, ?day: Integer) -> MonthDay

    def strftime: (String format) -> String

    def to_date: (Integer year) -> Date

    def as_json: (*untyped) -> String

    def to_s: () -> String

    def inspect: () -> String

    private

    def max_day: (Integer m) -> Integer
  end

  class TimeOfDay
    include Comparable

    attr_reader hour: Integer
    attr_reader minute: Integer
    attr_reader second: Integer

    def initialize: (Integer hour, Integer minute, ?Integer second) -> void

    def self.from: (Time time) -> TimeOfDay

    def self.from_seconds: (Integer total) -> TimeOfDay

    def self.parse: (String str) -> TimeOfDay

    def <=>: (TimeOfDay other) -> Integer
           | (untyped other) -> nil

    def +: (Integer seconds) -> TimeOfDay

    def -: (Integer seconds) -> TimeOfDay

    def advance: (?hours: Integer, ?minutes: Integer, ?seconds: Integer) -> TimeOfDay

    def change: (?hour: Integer, ?minute: Integer, ?second: Integer) -> TimeOfDay

    def to_seconds: () -> Integer

    def strftime: (String format) -> String

    def as_json: (*untyped) -> String

    def to_s: () -> String

    def inspect: () -> String
  end
end
